<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>Katas.Tests</RootNamespace>
        <TargetFramework>net9.0</TargetFramework>
        <!--
        To enable the Microsoft Testing Platform 'dotnet test' experience, add property:
          <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    
        To enable the Microsoft Testing Platform native command line experience, add property:
          <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    
        For more information on Microsoft Testing Platform support in xUnit.net, please visit:
          https://xunit.net/docs/getting-started/v3/microsoft-testing-platform
        -->
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions" Version="9.2.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Katas\Katas.csproj" />
    </ItemGroup>

</Project>
